/**
 * Fund Data Transformer
 * 
 * This script implements Phase 1 (item 3) of the data source roadmap:
 * - Reads raw CSV files from raw-data/
 * - Transforms data into unified JSON schema for UI layer
 * - Outputs to app/assets/data/ directory
 * 
 * **IMPORTANT**: This script must be run AFTER `transform-company-data.ts` 
 * as it requires the updated `company-list.json` file.
 * 
 * ## Usage
 * 
 * ```bash
 * npm run transform-company-data  # Run this first!
 * npm run transform-fund-data
 * ```
 * 
 * ## Input
 * 
 * - **Source 1**: `raw-data/XII. 基金排碳量資訊.csv`
 * - **Source 2**: `raw-data/所有基金與排碳大戶對照.csv`
 * - **Source 3**: `app/assets/data/company-list.json` (generated by transform-company-data.ts)
 * - **Format**: CSV with Chinese headers
 * 
 * ## Output
 * 
 * ### Fund List (`app/assets/data/fund-list.json`)
 * 
 * JSON array containing fund information:
 * 
 * ```typescript
 * interface FundData {
 *   基金代號: string;           // Fund code (e.g., "0050")
 *   基金名稱: string;           // Fund name
 *   總市值: number;            // Total market value in million NTD
 *   排碳大戶家數: number;       // Number of high-emission companies
 *   排碳大戶佔比: number;       // Percentage of high-emission companies in portfolio
 *   排碳大戶總碳排量: number;   // Total carbon emissions from high-emission holdings
 *   使用燃煤家數: number;       // Number of coal-using companies
 * }
 * ```
 * 
 * ### Per-Fund Company Lists (`app/assets/data/funds/[基金代號].json`)
 * 
 * JSON object containing fund metadata and filtered company data:
 * 
 * ```typescript
 * interface FundDetail {
 *   meta: FundData;           // Fund metadata from fund list
 *   companies: CompanyData[]; // Array of companies held by this fund
 * }
 * ```
 * 
 * ## Data Transformations
 * 
 * 1. **總市值 (Total Market Value)**
 *    - Source: `投資價值（萬）` in CSV
 *    - Calculation: `投資價值（萬）/ 100`
 *    - Unit: Million NTD
 * 
 * 2. **排碳大戶佔比 (High-Emission Company Ratio)**
 *    - Source: `排碳大戶家數` and `持股企業數` in CSV
 *    - Calculation: `(排碳大戶家數 / 持股企業數) * 100`
 *    - Unit: Percentage (rounded to 2 decimal places)
 * 
 * ## Implementation Notes
 * 
 * - Uses CSV parser that handles quoted fields and special characters
 * - Removes currency symbols ($) and thousand separators (,) when parsing numbers
 * - Logs all operations for transparency and traceability
 * - Follows the data source roadmap (Phase 1, item 3)
 * - Generates per-fund company lists by filtering company-list.json based on fund mappings
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { Logger } from './lib/logger.js';

// Get directory path for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Paths
const RAW_DATA_DIR = join(__dirname, '..', 'raw-data');
const OUTPUT_DIR = join(__dirname, '..', 'app', 'assets', 'data');
const FUNDS_OUTPUT_DIR = join(OUTPUT_DIR, 'funds');

/**
 * Company data interface (from company-list.json)
 */
interface CompanyData {
  公司: string;
  產業分類: string;
  '溫室氣體排放量（公噸二氧化碳當量）': string;
  淨零目標年: string;
  '2030 年減量目標設定': string;
  'SBTi 承諾': string;
  '>> 雷達圖數據': string;
  '2030年溫室氣體絕對減量目標': string;
  '2030年再生能源使用率目標': string;
  '2030年能源效率進步目標': string;
  '2024年再生能源使用率': string;
  '2022-2024年能源效率進步率': string;
  範疇三及減量策略: string;
  有具體減量策略: string;
  範疇三揭露: string;
  範疇三減量規劃: string;
  近三年能效進步率: string;
  節能目標設定: string;
  再生能源使用率: string;
  再生能源設置容量: string;
  是否完成用電大戶再生能源設置義務: string;
  中期再生能源目標設定: string;
  'RE100 承諾': string;
  '燃煤使用量（公噸）': string;
  代表縣市: string;
  事業統編: string;
  公司全名: string;
}

/**
 * Parse CSV string to array of objects
 */
function parseCSV(csvContent: string): Record<string, string>[] {
  const lines = csvContent.split('\n').filter(line => line.trim());
  
  if (lines.length === 0) {
    return [];
  }

  // Parse header
  const headers = parseCSVLine(lines[0]);
  
  // Parse data rows
  const data: Record<string, string>[] = [];
  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i]);
    if (values.length === 0) continue;
    
    const row: Record<string, string> = {};
    headers.forEach((header, index) => {
      row[header] = values[index] || '';
    });
    data.push(row);
  }
  
  return data;
}

/**
 * Parse a single CSV line, handling quoted fields
 */
function parseCSVLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;
  
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    const nextChar = line[i + 1];
    
    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        // Escaped quote
        current += '"';
        i++; // Skip next quote
      } else {
        // Toggle quote mode
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      // End of field
      result.push(current);
      current = '';
    } else {
      current += char;
    }
  }
  
  // Add last field
  result.push(current);
  
  return result;
}

/**
 * Parse a number string from CSV (handles $ and commas)
 */
function parseNumber(value: string): number {
  if (!value || value === '') return 0;
  // Remove $, commas, and whitespace
  const cleaned = value.replace(/[$,\s]/g, '');
  const num = parseFloat(cleaned);
  return isNaN(num) ? 0 : num;
}

/**
 * Fund data interface
 */
interface FundData {
  基金代號: string;
  基金名稱: string;
  總市值: number; // in million NTD
  排碳大戶家數: number;
  排碳大戶佔比: number; // percentage
  排碳大戶總碳排量: number;
  使用燃煤家數: number;
}

/**
 * Transform fund list data
 */
function transformFundList(rawData: Record<string, string>[]): FundData[] {
  return rawData.map(row => {
    const 投資價值萬 = parseNumber(row['投資價值（萬）']);
    const 持股企業數 = parseNumber(row['持股企業數']);
    const 排碳大戶家數 = parseNumber(row['排碳大戶家數']);
    
    return {
      基金代號: row['基金代號'] || '',
      基金名稱: row['基金名稱'] || '',
      總市值: Math.round(投資價值萬 / 100), // Convert 萬 to million
      排碳大戶家數,
      排碳大戶佔比: 持股企業數 > 0 ? Math.round((排碳大戶家數 / 持股企業數) * 10000) / 100 : 0, // Percentage with 2 decimal places
      排碳大戶總碳排量: parseNumber(row['大戶總碳排量']),
      使用燃煤家數: parseNumber(row['總燃煤企業數']),
    };
  });
}

/**
 * Generate per-fund company lists
 * Maps companies to their respective funds and filters company data
 * Only generates lists for funds that exist in the fund list
 */
function generateFundCompanyLists(
  fundMappingData: Record<string, string>[],
  companyListData: CompanyData[],
  fundList: FundData[],
  logger: Logger
): Map<string, CompanyData[]> {
  // Create a map of fund code -> fund metadata
  const fundMetaMap = new Map<string, FundData>();
  fundList.forEach(fund => {
    fundMetaMap.set(fund.基金代號, fund);
  });

  // Create a map of fund code -> list of company names
  const fundToCompanies = new Map<string, Set<string>>();
  
  fundMappingData.forEach(row => {
    const fundCode = row['基金代號'];
    const companyName = row['公司'];
    
    if (!fundCode || !companyName) return;
    
    // Only process funds that exist in the fund list
    if (!fundMetaMap.has(fundCode)) {
      return;
    }
    
    if (!fundToCompanies.has(fundCode)) {
      fundToCompanies.set(fundCode, new Set());
    }
    fundToCompanies.get(fundCode)!.add(companyName);
  });
  
  logger.info(`Found ${fundToCompanies.size} funds (from fund list) in mapping data`);
  
  // Create a map of company name -> company data for quick lookup
  const companyMap = new Map<string, CompanyData>();
  companyListData.forEach(company => {
    companyMap.set(company.公司, company);
  });
  
  // Generate filtered company lists for each fund
  const fundCompanyLists = new Map<string, CompanyData[]>();
  
  fundToCompanies.forEach((companyNames, fundCode) => {
    const companies: CompanyData[] = [];
    
    companyNames.forEach(companyName => {
      const companyData = companyMap.get(companyName);
      if (companyData) {
        companies.push(companyData);
      } else {
        logger.info(`[WARNING] Company "${companyName}" in fund ${fundCode} not found in company-list.json`);
      }
    });
    
    fundCompanyLists.set(fundCode, companies);
    logger.info(`Fund ${fundCode}: ${companies.length} companies`);
  });
  
  return fundCompanyLists;
}

/**
 * Main transformation function
 */
async function transformFundData() {
  const logger = new Logger();

  try {
    logger.info('Starting fund data transformation');
    logger.info('='.repeat(60));

    // Read fund list CSV
    const fundListCsvPath = join(RAW_DATA_DIR, 'XII. 基金排碳量資訊.csv');
    logger.info(`Reading fund list CSV from: ${fundListCsvPath}`);
    
    const fundListCsvContent = readFileSync(fundListCsvPath, 'utf-8');
    const fundListRawData = parseCSV(fundListCsvContent);
    
    logger.info(`Parsed ${fundListRawData.length} fund records from fund list CSV`);

    // Read fund-company mapping CSV
    const fundMappingCsvPath = join(RAW_DATA_DIR, '所有基金與排碳大戶對照.csv');
    logger.info(`Reading fund-company mapping CSV from: ${fundMappingCsvPath}`);
    
    const fundMappingCsvContent = readFileSync(fundMappingCsvPath, 'utf-8');
    const fundMappingRawData = parseCSV(fundMappingCsvContent);
    
    logger.info(`Parsed ${fundMappingRawData.length} fund-company mapping records`);

    // Read company list JSON
    const companyListPath = join(OUTPUT_DIR, 'company-list.json');
    logger.info(`Reading company list from: ${companyListPath}`);
    
    let companyListData: CompanyData[];
    try {
      const companyListContent = readFileSync(companyListPath, 'utf-8');
      companyListData = JSON.parse(companyListContent);
      logger.info(`Loaded ${companyListData.length} company records`);
    } catch (error) {
      logger.error('Failed to read company-list.json', error);
      logger.error('Please run transform-company-data.ts first!');
      process.exit(1);
    }

    logger.info('='.repeat(60));

    // Transform fund list
    const fundList = transformFundList(fundListRawData);
    logger.success(`Transformed ${fundList.length} fund records`);

    // Generate per-fund company lists
    logger.info('Generating per-fund company lists...');
    const fundCompanyLists = generateFundCompanyLists(
      fundMappingRawData,
      companyListData,
      fundList,
      logger
    );

    // Create output directories
    mkdirSync(OUTPUT_DIR, { recursive: true });
    mkdirSync(FUNDS_OUTPUT_DIR, { recursive: true });
    logger.info(`Output directory: ${OUTPUT_DIR}`);
    logger.info(`Funds output directory: ${FUNDS_OUTPUT_DIR}`);

    // Write fund list JSON
    const fundListPath = join(OUTPUT_DIR, 'fund-list.json');
    writeFileSync(
      fundListPath,
      JSON.stringify(fundList, null, 2),
      'utf-8'
    );
    logger.success(`Saved fund list to: fund-list.json`);

    // Create a map of fund code -> fund metadata for writing fund details
    const fundMetaMap = new Map<string, FundData>();
    fundList.forEach(fund => {
      fundMetaMap.set(fund.基金代號, fund);
    });

    // Write per-fund company list JSONs with metadata
    let savedFundFiles = 0;
    fundCompanyLists.forEach((companies, fundCode) => {
      const fundMeta = fundMetaMap.get(fundCode);
      if (!fundMeta) {
        logger.info(`[WARNING] Fund ${fundCode} metadata not found, skipping file creation`);
        return;
      }

      const fundDetail = {
        meta: fundMeta,
        companies: companies
      };

      const fundFilePath = join(FUNDS_OUTPUT_DIR, `${fundCode}.json`);
      writeFileSync(
        fundFilePath,
        JSON.stringify(fundDetail, null, 2),
        'utf-8'
      );
      savedFundFiles++;
    });
    logger.success(`Saved ${savedFundFiles} fund company lists to: funds/`);

    // Log sample of transformed data
    logger.info('='.repeat(60));
    logger.info('Sample of fund list data (first 3 records):');
    console.log(JSON.stringify(fundList.slice(0, 3), null, 2));

    // Log sample of fund company list with new schema
    const firstFund = fundList[0];
    if (firstFund && fundCompanyLists.has(firstFund.基金代號)) {
      const firstFundCompanies = fundCompanyLists.get(firstFund.基金代號)!;
      const firstFundDetail = {
        meta: firstFund,
        companies: firstFundCompanies.slice(0, 2)
      };
      logger.info(`Sample of fund ${firstFund.基金代號} detail (with first 2 companies):`);
      console.log(JSON.stringify(firstFundDetail, null, 2));
    }

    // Summary
    logger.info('='.repeat(60));
    logger.success('Data transformation completed successfully');
    logger.info(`Total funds processed: ${fundList.length}`);
    logger.info(`Total fund company lists generated: ${savedFundFiles}`);
    logger.logDuration();
    logger.info('='.repeat(60));

  } catch (error) {
    logger.error('Fatal error during data transformation', error);
    process.exit(1);
  }
}

// Run the script
transformFundData();
